### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by ragsinator** [tjhorner/dancing-ponies#2]
A volume sensitivity slider/button would be nice. That way people can watch twilight dance without turning up the volume too loud.

**Comment by tjhorner** [comment]
The program isn't affected by Windows' master volume slider, so you could have your volume at 0 and she would still dance. It depends on the application's volume.

**Comment by tjhorner** [comment]
Example:

If I change the master volume of my headset, the application won't respond.

![](http://puu.sh/iOAkK/4ece454103.gif)

If I were to change Chrome's volume, then it would be affected:

![](http://puu.sh/iOAwu/547951185c.gif)
