### ISSUE TITLE
Does not work on mac or linux.

### ISSUE THREAD

**Issue by tetra-fox** [tjhorner/dancing-ponies#5]
@tjhorner #1 #4 #4 

- [ ] 

- 

`[1. ]([url](

**_## url_**

))`

**Comment by tjhorner** [comment]
duplicate of #1

**Comment by tetra-fox** [comment]
oh .-.

**Comment by tjhorner** [comment]
lol

**Comment by tetra-fox** [comment]
Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.Does not work on mac or linux.

**Comment by tjhorner** [comment]
Fixed
